export const gamesArray = [
    {
        id: 'csgo',
        name: 'Counter-Strike: Global Offensive',
        developer: 'Valve Corporation',
        image: 'csgo.png',
        description: 'a competitive first-person shooter game',
        category: 'fps',
        price: 15.00,
        onSale: false,
    },
    {
        id: 'among-us',
        name: 'Among Us',
        developer: 'Innersloth',
        image: 'among-us.jpg',
        description: 'a party game in which players try to outsmart each other',
        category: 'party-game',
        price: 5.00,
        onSale: false,
    },
    {
        id: 'for-the-king',
        name: 'For the King',
        developer: 'Iron Oak Games',
        image: 'for-the-king.jpg',
        description: 'an rpg style rogue-like adventure game',
        category: 'rpg',
        price: 20.00,
        onSale: false,
    },
    {
        id: 'l4d2',
        name: 'Left 4 Dead 2',
        developer: 'Valve Corporation',
        image: 'left-4-dead-2.jpg',
        description: 'a zombie survival game where four players must battle through hordes of undead',
        category: 'fps',
        price: 10.00,
        onSale: false,
    },
    {
        id: 'stardew-valley',
        name: 'Stardew Valley',
        developer: 'ConcernedApe',
        image: 'stardew-valley.jpg',
        description: 'rpg style game focused on being a farmer and interacting with the people of Pelican Town',
        category: 'rpg',
        price: 15.00,
        onSale: false,
    },
]